// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a session-mode connection. Supabase's transaction pooler
    // (port 6543) cannot run them, but it is what the app uses at runtime,
    // because session mode caps at 15 clients and serverless exhausts that.
    // Falls back to DATABASE_URL so a single-connection setup still works.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
