-- Quiet hours for follow-ups, and a way for a person to say stop.
--
-- Strictly additive. Every column is either nullable or has a default, so this
-- applies to a live table without a rewrite and without a backfill.
--
-- NOTE ON WHAT IS DELIBERATELY ABSENT FROM THIS FILE.
--
-- `prisma migrate diff` generated a `DROP INDEX
-- "KnowledgeChunk_embedding_hnsw_idx"` at the top of this migration and it has
-- been removed by hand. That index is created in raw SQL in
-- 20260904230000_add_chunk_embeddings because the column is
-- Unsupported("vector(384)"), which Prisma's datamodel cannot describe. So the
-- diff sees an index it did not create, decides it is drift, and helpfully
-- proposes deleting it.
--
-- Dropping it would not fail anything. Semantic search would keep returning
-- results, by sequential scan over every chunk in the table, getting quietly
-- slower as the knowledge base grows. That is the worst shape a regression can
-- take, so it is called out here rather than left to be rediscovered.
--
-- Any future migration generated by diff will propose the same drop. Strip it
-- again.

-- Quiet hours. The window gates follow-ups only; a campaign's first reply is
-- never held, because the person just commented asking for it.
ALTER TABLE "Workspace"
  ADD COLUMN "timezone"          TEXT    NOT NULL DEFAULT 'UTC',
  ADD COLUMN "quietHoursEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "quietHoursStart"   INTEGER NOT NULL DEFAULT 21,
  ADD COLUMN "quietHoursEnd"     INTEGER NOT NULL DEFAULT 9;

-- Hours are wall-clock hours. Anything outside 0-23 would make isQuietHour
-- silently never match, which reads as "quiet hours are broken" rather than as
-- "that value is invalid", so the database refuses it instead.
ALTER TABLE "Workspace"
  ADD CONSTRAINT "Workspace_quiet_hours_range"
  CHECK (
    "quietHoursStart" BETWEEN 0 AND 23
    AND "quietHoursEnd" BETWEEN 0 AND 23
  );

-- Opt-out. Null means they never asked to stop.
ALTER TABLE "Contact" ADD COLUMN "optedOutAt" TIMESTAMP(3);

-- Every send path filters on this, always alongside the workspace or account
-- scope it already carries. Partial, because the opted-out set stays small and
-- an index over the nulls would be almost the whole table.
CREATE INDEX "Contact_optedOutAt_idx"
  ON "Contact" ("workspaceId", "optedOutAt")
  WHERE "optedOutAt" IS NOT NULL;
